name: Publish Package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: "Publish library"
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install dependencies
        run: pip install dunamai

      - name: Build package
        run: |
          VERSION=$(dunamai from any --no-metadata --style pep440)
          poetry version $VERSION
          poetry build

      - name: Release to PyPI
        run: |
          poetry publish -u __token__ -p ${{ secrets.PYPI_API_TOKEN }} || \
            echo 'Version exists'